<template>
    <div class="modal fade modal_create_avatar" ref="avatarModal" id="exampleModalCenter" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Customize Avatar</h5>
                </div>
                <div class="modal-body">
                    <form @submit.prevent="submit">
                        <div class="hello">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-12">
                                        <h1>{{ msg }}</h1>
                                        <div class="btnCont">
                                            <button class="themeBtn" @click="randomize()">Generate Random</button>
                                            <button class="themeBtn" @click="generateAvatar()">Generate Avatar</button>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <figure class="sticky avatarImg">

                                            <img :src="avatar.url" width="350" alt="avatar"/>
                                        </figure>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="fieldsBox">
                                            <div class="form-group">
                                                <label for="gender">Gender </label>
                                                <select class="form-control" id="gender" v-model="choices.gender" @change="changeStyle()">
                                                    <option v-for="gender in libMojiData.genders" :value="gender[1]">
                                                        {{ gender[0] }}
                                                    </option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="styles">Styles </label>
                                                <select class="form-control" id="styles" v-model="choices.style" @change="changeStyle()">
                                                    <option value="1">bitmoji</option>
                                                    <!--          <option v-for="style in libMojiData.styles" :value="style[1]">{{ style[0] }}</option>-->
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="poses">Poses </label>
                                                <select class="form-control" id="poses" v-model="choices.pose" @change="generateAvatar()">
                                                    <option v-for="pose in libMojiData.poses" :value="pose">{{pose}}
                                                    </option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="brand">Brands </label>
                                                <select class="form-control" id="brand" v-model="choices.brand" @change="generateOutfits()">
                                                    <option v-for="(brand, key) in libMojiData.brands" :value="key">
                                                        {{ brand.name }}
                                                    </option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="outfit">Outfit </label>
                                                <select class="form-control" id="outfit" v-model="choices.outfit" @change="generateAvatar()">
                                                    <option v-for="(outfit, key) in libMojiData.outfits" :value="key">{{slugs[choices.gender - 1].outfits[outfit.outfit] ?? outfit.outfit}}
                                                    </option>
                                                </select>
                                            </div>
                                            <div class="form-group" v-if="choices.pose == 'body'">
                                                <label for="rotation">Rotation </label>
                                                <select class="form-control" id="rotation" v-model="choices.rotation" @change="generateAvatar()">
                                                    <option value="0">Straight</option>
                                                    <option value="1">Right</option>
                                                    <option value="7">Left</option>
                                                </select>
                                            </div>
                                            <br v-if="choices.pose == 'body'">
                                            <div class="form-group" v-for="(traits, key) in libMojiData.traits">
                                                <label :for="traits.key">{{ traits.key }}&nbsp;</label>
                                                <select class="form-control" :id="traits.key" v-model="choices.traits[traits.key]" :key="key"
                                                        @change="generateAvatar()">
                                                    <option v-for="(trait, key) in traits.options" :value="trait.value">
                                                        {{ slugs[choices.gender - 1].traits[(traits.key).toString() + ' ' + (key + 1).toString()] ?? (traits.key).toString() + ' ' + (key + 1).toString() }}
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                        <!--                                        <button @click="generateAvatar()">Generate Avatar</button>-->
                                        <button class="themeBtn" @click="profileImgUpload()">Confirm</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!--                <div class="modal-footer">-->
                <!--                    <button type="button" class="btn btn-primary" @click.prevent="sendInvite()">Send</button>-->
                <!--                </div>-->
            </div>
        </div>
    </div>
</template>

<script>
import libmoji from "libmoji";
import {useForm} from "@inertiajs/inertia-vue3";

export default {
    name: 'CreateAvatar',
    data() {
        return {
            form: useForm({
                url: ''
            }),
            choices: {
                gender: 1,
                genderStr: '',
                style: 1,
                styleStr: '',
                pose: 'body',
                brand: 0,
                traits: {},
                outfit: 0,
                rotation: 0,
            },
            avatar: {
                url: '',
                gender: '',
                style: '',
                traits: '',
                outfit: '',
            },
            libMojiData: {
                genders: {},
                styles: {},
                poses: {},
                traits: {},
                outfits: {},
                brands: {},
            },
            slugs: [
                {
                    outfits: {
                        "baresc1a": "Casual Black",
                        "baresc1b": "Navy Green",
                        "baresc1c": "Black Tee",
                        "baresc1d": "Grey Casual Fit",
                        "baresc3a": "White Jersey with Grey Sweatpants",
                        "baresc3b": "Red Jersey with Black Jeans",
                        "baresc3c": "Dark Blue Jersey with Blank Pants",
                        "baresc3d": "Black Fit Jersey",
                        "baresc5a": "Red Gingham Check Shirt",
                        "baresc5b": "Brown Check Shirt",
                        "baresc5c": "Black Over-All Fit",
                        "baresc7a": "Blue Checkered Casual Fit",
                        "baresc7b": "Red Checkered Casual Fit",
                        "baresc7c": "Black and Pink Casual Fit",
                        "baresc9a": "Punk Black Fit",
                        "baresc9b": "Red and Black Punk Fit",
                        "baresc9c": "Black Casual Fit",
                        "baresc11a": "Black Gothic Fit",
                        "baresc11b": "Grey and Black Goth Fit",
                        "baresc11c": "White Goth Fit",
                        "baresc11d": "Yellow and Green Goth Fit",
                    },
                    traits: {
                        "beard 1": "No Beard",
                        "beard 2": "Subtle Beard",
                        "beard 3": "French Beard",
                        "beard 4": "Full French Beard",
                        "beard 5": "Ducktail Beard",
                        "beard 6": "Banholdz Beard",
                        "beard 7": "Moustache",
                        "beard 8": "Anchor Beard",
                        "beard 9": "Anchor Beard with a Moustache",
                        "beard 10": "Moustache with Subtle Beard",
                        "beard 11": "Soul Patch with Subtle Beard",
                        "beard 12": "Soul Patch with Moustache and Subtle Beard",
                        "beard 13": "Circle Beard",
                        "brow 1": "Straight Brows",
                        "brow 2": "Black Tail Arch",
                        "brow 3": "Hard Angled Brows",
                        "brow 4": "Downward Brows",
                        "brow 5": "Long Brows",
                        "brow 6": "Soft S-Shaped Brows",
                        "brow 7": "Medium S-Shaped Brows",
                        "brow 8": "Soft Angle with Medium Arch",
                        "brow 9": "Managerial Brows",
                        "brow 10": "Thick Gradual Brows",
                        "brow 11": "Bushy Brows",
                        "brow 12": "High Arch Brows",
                        "brow 13": "Round Bushy Brows",
                        "brow 14": "Bushy S-Shaped Brows",
                        "brow 15": "Straight Bushy Brows",
                        "brow 16": "Thick High Arch Brows",
                        "brow 17": "Thick Downward Brows",
                        "brow 18": "Medium Downward Brows",
                        "brow 19": "Hard Angled Brows",
                        "brow 20": "Soft Arch Brows",
                        "brow 21": "Sleek Brows",
                        "brow 22": "Long Sleek Brows",
                        "brow 23": "Sleek Thin Brows",
                        "brow 24": "High Sleek Thin Brows",
                        "brow 25": "Thin Round Brows",
                        "brow 26": "Thick Straight Brows",
                        "brow 27": "Straight Sleek Brows",
                        "brow 28": "Sharp Angled Round Brow",
                        "brow 29": "Bushy Round Brows",
                        "brow 30": "Sleek Round Brows",
                        "brow 31": "Sharp Round and Long Brows",
                        "brow 32": "Sleek Downward Brows",
                        "brow 33": "Straight Thick Brows",
                        "cheek_details 1": "Normal Cheeks",
                        "cheek_details 2": "Heart Shape",
                        "cheek_details 3": "Triangle Cheeks",
                        "cheek_details 4": "Rectangle Cheeks",
                        "cheek_details 5": "Diamond Cheeks",
                        "cheek_details 6": "Oblong Cheeks",
                        "cheek_details 7": "Heptagon Cheeks",
                        "cheek_details 8": "Detailed Cheekbones",
                        "cheek_details 9": "Heart Shaped Cheeks",
                        "cheek_details 10": "V-Triangle Cheeks",
                        "cheek_details 11": "High Cheek Bones",
                        "cheek_details 12": "Mole Under Eye",
                        "ear 1": "Square Ears",
                        "ear 2": "Pointed Ears",
                        "ear 3": "Round Ears",
                        "ear 4": "Narrow Ears",
                        "ear 5": "Sticking Out Ears",
                        "ear 6": "Long Ears",
                        "ear 7": "Narrow and Long Ears",
                        "ear 8": "Pointed and Narrow Ears",
                        "ear 9": "Round Ear",
                        "earring 1": "No Earring",
                        "earring 2": "Ear-ring",
                        "earring 3": "Stud",
                        "eye 1": "Almond Eyes",
                        "eye 2": "Monolid Eyes",
                        "eye 3": "Protruding Eyes",
                        "eye 4": "Prominent Eyes",
                        "eye 5": "Deep Set Eyes",
                        "eye 6": "Droopy Hooded Eyes",
                        "eye 7": "Hooded Eyes",
                        "eye 8": "Thin Almond Eyes",
                        "eye 9": "Asian Eyes",
                        "eye 10": "Roundish-Asian Eyes",
                        "eye 11": "Round Shaped Eyes",
                        "eye 12": "Big Round Eyes",
                        "eye 13": "Droopy Eyes",
                        "eye 14": "Downward Eyes",
                        "eye 15": "Big Droopy Hooded Eyes",
                        "eye 16": "Long Hooded Eyes",
                        "eye 17": "Round Eyes",
                        "eye 18": "Small Asian Eyes",
                        "eyelash 1": "No Lash",
                        "eyelash 2": "Small Lashes",
                        "eyelash 3": "Outward Lashes",
                        "eyelash 4": "Rounded Lashe",
                        "eye_details 1": "No Detail",
                        "eye_details 2": "Under Eye Line",
                        "eye_details 3": "eye_details 3",
                        "eye_details 4": "Fine Lines",
                        "eye_details 5": "Under Eye and Fine Lines",
                        "eye_details 6": "Wrinkles",
                        "eye_details 7": "Under Bags",
                        "eye_details 8": "Under Eye Lin",
                        "face_lines 1": "No face_lines",
                        "face_lines 2": "Forehead Line",
                        "face_lines 3": "Forehead Lines 2",
                        "face_lines 4": "Forehead Earth Line",
                        "face_lines 5": "Forehead Earth Line",
                        "face_lines 6": "Frown Line",
                        "face_lines 7": "No Animations",
                        "face_lines 8": "Repeated Animations",
                        "face_lines 9": "Repeated Animations",
                        "face_lines 10": "Repeated Animations",
                        "face_lines 11": "Crow Lines with Forehead Lines",
                        "face_lines 12": "Repeated Animations",
                        "face_lines 13": "Repeated Animations",
                        "face_lines 14": "Repeated Animations",
                        "glasses 1": "No Glasses",
                        "glasses 2": "Square Glasses",
                        "glasses 3": "Thick Square Glasses",
                        "glasses 4": "Brown Square Glasses",
                        "glasses 5": "Thick Square Brown Glasses",
                        "glasses 6": "Round Glasses",
                        "glasses 7": "Thick Round Glasses",
                        "glasses 8": "Rectangle Glasses",
                        "glasses 9": "Light Rectangle Glasses",
                        "glasses 10": "Opaque Rectangle Glasses",
                        "glasses 11": "Rectangle Sunglasses",
                        "glasses 12": "Thick Rectangle Glasses",
                        "glasses 13": "Thick Rectangle Glasses with Shade",
                        "glasses 14": "Thick Rectangle Shades",
                        "glasses 15": "Opaque Thick Rectangle Shades",
                        "glasses 16": "Geometric Glasses",
                        "glasses 17": "Geometric Glasses with Shades",
                        "glasses 18": "Geometric Sunglasses",
                        "glasses 19": "Geometric Sunglasses with Shades",
                        "glasses 20": "Thick Din Glasses",
                        "glasses 21": "Thick Din Glasses with Shade",
                        "glasses 22": "Thick Din Sunglasses",
                        "glasses 23": "Thick Din Sunglasses with Shade",
                        "glasses 24": "American Typewriter",
                        "glasses 25": "American Typewriter with Shade",
                        "glasses 26": "American Typewriter Sunglasses",
                        "glasses 27": "American Typewriter Sunglasses with Shade",
                        "glasses 28": "Thick Helvetica",
                        "glasses 29": "Thick Helvetica with Shade",
                        "glasses 30": "Thick Helvetica Sunglasses",
                        "glasses 31": "Thick Helvetica with Shade",
                        "glasses 32": "Times New Roman",
                        "glasses 33": "Times New Roman with Shade",
                        "glasses 34": "Times New Roman Sunglasses",
                        "glasses 35": "Times New Roman Sunglasses with Shade",
                        "glasses 36": "Times New Roman Sunglasses with Shade",
                        "glasses 37": "Butterfly Glasses",
                        "glasses 38": "Butterfly Glasses with Shade",
                        "glasses 39": "Butterfly Sunglasses",
                        "glasses 40": "Butterfly Sunglasses with Shade",
                        "glasses 41": "Aviator Glasses",
                        "glasses 42": "Aviator Glasses with Shade",
                        "glasses 43": "Aviator See-through Glasses",
                        "glasses 44": "Aviator Glasses with Shade",
                        "glasses 45": "Aviator Sunglasses",
                        "glasses 46": "Aviator Sunglasses with Shade",
                        "glasses 47": "Round Glasses",
                        "glasses 48": "Round See-through Glasses",
                        "glasses 49": "Round Sunglasses with Shade",
                        "glasses 50": "Round Sunglasses",
                        "glasses 51": "Round Sunglasses with Shade",
                        "glasses 52": "Eye Patch",
                        "glasses 53": "Monocle",
                        "glasses 54": "[Repeated",
                        "glasses 55": "[Repeated",
                        "glasses 56": "[Repeated",
                        "glasses 57": "[Repeated",
                        "glasses 58": "[Repeated",
                        "glasses 59": "Polarized Sunglasses",
                        "glasses 60": "[Repeated",
                        "glasses 61": "[Repeated",
                        "glasses 62": "[Repeated",
                        "glasses 63": "[Repeated",
                        "glasses 64": "[Repeated",
                        "glasses 65": "Bifocal Glasses",
                        "glasses 66": "Bifocal See-through Glasses",
                        "glasses 67": "Bifocal Glasses with Shade",
                        "glasses 68": "Bifocal Sunglasses",
                        "glasses 69": "Bifocal Sunglasses with Shade",
                        "glasses 70": "Half Frame Glasses",
                        "glasses 71": "Half Frame See-through Glasses",
                        "glasses 72": "Half Frame Glasses with Shade",
                        "glasses 73": "Half Frame Sunglasses",
                        "glasses 74": "Half Frame Sunglasses with Shade",
                        "glasses 75": "Star Glasses",
                        "glasses 76": "Thick Round Glasses",
                        "glasses 77": "Green Round Glasses",
                        "glasses 78": "Heart Shaped Glasses",
                        "glasses 79": "Round, Funny Glasses",
                        "glasses 80": "Funny Glasses",
                        "glasses 81": "Semi-Rimless Glasses",
                        "glasses 82": "Zorro Mask",
                        "hair 1": "Short Hair.",
                        "hair 2": "Black Short Hair.",
                        "hair 3": "Black Faux Hawk.",
                        "hair 4": "Long Black Faux Hawk.",
                        "hair 5": "Long Black Faux Hawk.",
                        "hair 6": "Side Fringe Hair-Up.",
                        "hair 7": "Side Fringe-Up.",
                        "hair 8": "Messy Hair.",
                        "hair 9": "Short Black Quiff.",
                        "hair 10": "Black Side-Ways.",
                        "hair 11": "Black Side-Parted.",
                        "hair 12": "Short Side-Parted.",
                        "hair 13": "Black Wavy Hair.",
                        "hair 14": "Black Fringe Side Part.",
                        "hair 15": "Long Black Messy Hair.",
                        "hair 16": "Fringe Black Messy Hair.",
                        "hair 17": "Short Black Hair.",
                        "hair 18": "Black Buzzcut.",
                        "hair 19": "Side Fringe.",
                        "hair 20": "Black Fringe Up.",
                        "hair 21": "Black Diamond Hair.",
                        "hair 22": "Short Wavy Hairstyle With Bangs",
                        "hair 23": "Left Side Quiff Up.",
                        "hair 24": "Black Hair Down.",
                        "hair 25": "Wavy Side Hair.",
                        "hair 26": "Short Fringe Back Combed Hair.",
                        "hair 27": "Long Fringe Back Combed Hair.",
                        "hair 28": "Wavy Front Hair.",
                        "hair 29": "Fringe Hair.",
                        "hair 30": "Black Short Wavy Hair.",
                        "hair 31": "Wavy Faux Hawk.",
                        "hair 32": "The Crown.",
                        "hair 33": "Puffy Crown.",
                        "hair 34": "Buzzcut.",
                        "hair 35": "Curl Buzzcut.",
                        "hair 36": "Puffy Curl Buzzcut.",
                        "hair 37": "Black Curl Back Combed.",
                        "hair 38": "Short, Black, Curl Buzzcut.",
                        "hair 39": "Black, Short Curl.",
                        "hair 40": "Military Haircut.",
                        "hair 41": "Side Flat Haircut.",
                        "hair 42": "Long Flat.",
                        "hair 43": "Dreadlocks.",
                        "hair 44": "Side Fringe.",
                        "hair 45": "Combed Back Hair Cut.",
                        "hair 46": "Curl Combed Back Hair Cut.",
                        "hair 47": "Wave Combed Back.",
                        "hair 48": "Side Hair.",
                        "hair 49": "Fringe Side Ways Hair.",
                        "hair 50": "Side Ways with Bald Patch.",
                        "hair 51": "Side Hair with Bald Patch.",
                        "hair 52": "Bald.",
                        "hair 53": "Subtle Hair.",
                        "hair 54": "Spikes.",
                        "hair 55": "Mohawk Haircut.",
                        "hair 56": "Long Mohawk with Subtle Hair.",
                        "hair 57": "Black Middle Mohawk.",
                        "hair 58": "Mid Mohawk with Full Hair.",
                        "hair 59": "Wavy Side Hair.",
                        "hair 60": "Black Spikes.",
                        "hair 61": "Temple Fade with Sponge Twists.",
                        "hair 62": "FroHawk Haircut.",
                        "hair 63": "Long Black Messy Hair.",
                        "hair 64": "S-Shaped Curl.",
                        "hair 65": "Side Parted Black Hair.",
                        "hair 66": "Side Parted Long Black Hair.",
                        "hair 67": "Long Front Black Hair.",
                        "hair 68": "Long Black Hair.",
                        "hair 69": "Puffy Black Hair.",
                        "hair 70": "Side Part Long.",
                        "hair 71": "Long Parted Black Hair.",
                        "hair 72": "Front Long Hair.",
                        "hair 73": "Grown-Out Black Hair.",
                        "hair 74": "Long Black Grown-Out Black Hair.",
                        "hair 75": "Medium Wavy Hair.",
                        "hair 76": "Medium Side Parted Black Hair.",
                        "hair 77": "Medium Bob.",
                        "hair 78": "Wavy Side Part.",
                        "hair 79": "Medium Side Part Hair.",
                        "hair 80": "Wavy Middle Part.",
                        "hair 81": "Black Long Fringe Haircut.",
                        "hair 82": "Black Long Wavy Haircut.",
                        "hair 83": "REPEATED.",
                        "hair 84": "Side Parted Long Haircut.",
                        "hair 85": "Medium Wavy Hair.",
                        "hair 86": "Curl Side Parted.",
                        "hair 87": "Drop Fade and Curls.",
                        "hair 88": "Drop Fade and Wave.",
                        "hair 89": "Triangle-Shaped Black Hair.",
                        "hair 90": "Black Buzzcut.",
                        "hair 91": "Long Middle Part Hair.",
                        "hair 92": "Long Over Grown Hair.",
                        "hair 93": "Long Side Parted.",
                        "hair 94": "Long Side Parted with Bangs.",
                        "hair 95": "Long Middle Parted.",
                        "hair 96": "Long Hair with Spikes.",
                        "hair 97": "Long Hair with Long Bangs.",
                        "hair 98": "Middle Part with Side Curls.",
                        "hair 99": "Long Straight Hair.",
                        "hair 100": "Black Long Hair.",
                    }
                },
                {
                    outfits: {
                        "baresc1a": "Causal Pink Shirt",
                        "baresc1b": "Black Tee with Checkered Pants",
                        "baresc1c": "Casual Green Shirt",
                        "baresc1d": "Crop-top with Fit Pants",
                        "baresc3a": "Sleeveless Shirt with Causal Pants",
                        "baresc3b": "Full Sleeves Shirt with Formal Pants",
                        "baresc3c": "Off-shoulder top with regular casual pants",
                        "baresc3d": "Sunny Side Green Outfit",
                        "baresc5a": "Urban Set Outfit Black shirt and Green Pants",
                        "baresc5b": "Yellow Shirt with White Pants",
                        "baresc5c": "Black Jumpsuit",
                        "baresc7a": "Light Purple Crop-top with Navy Blue Skirt",
                        "baresc7b": "Women Safari Outfit",
                        "baresc7c": "Ripped Jeans with Baggy White Shirt",
                        "baresc9a": "Casual College Outfit",
                        "baresc9b": "Women's High Waist (Brown) with Causal Beige Pants",
                        "baresc9c": "Trendy Back-to-School Outfit",
                        "baresc11a": "White Tee with Jeans Mini Skirt",
                        "baresc11b": "Beige Tee with Navy Blue Ripped Skirt",
                        "baresc11c": "Women White Tank top with Jeans and Long Coat",
                        "baresc11d": "Off-the-Shoulder Black Dress",
                    },
                    traits: {
                        "brow 1": "Rounded",
                        "brow 2": "Titled Downward",
                        "brow 3": "Thick Angled",
                        "brow 4": "Short and Thick",
                        "brow 5": "Raised Upward",
                        "brow 6": "Deeply Rounded",
                        "brow 7": "Curved",
                        "brow 8": "Straight",
                        "brow 9": "Slightly Angled",
                        "brow 10": "Curved Upside Down",
                        "brow 11": "Thin and Round",
                        "brow 12": "Frowny",
                        "brow 13": "Parallel",
                        "brow 14": "Sharp",
                        "brow 15": "Short Angle",
                        "brow 16": "Soft Angle",
                        "brow 17": "S-Angle",
                        "brow 18": "V Angle",
                        "brow 19": "Modern",
                        "brow 20": "Hard Angle",
                        "brow 21": "Strongly Angled",
                        "brow 22": "Slightly Titled",
                        "brow 23": "Thick Short Angled Brows",
                        "brow 24": "Sharply Angled and Titled",
                        "brow 25": "Thick and Slightly Angled",
                        "brow 26": "Thick Outward",
                        "brow 27": "Thick and Round",
                        "brow 28": "Slight Arch with Thickness",
                        "brow 29": "Sharply Arched",
                        "brow 30": "Raised Outward",
                        "brow 31": "Thick and Titled",
                        "brow 32": "Multiple Angles",
                        "brow 33": "Short & Balanced",
                        "eye 1": "Almond Eyes.",
                        "eye 2": "No Lid Eyes.",
                        "eye 3": "Fallen and Long Eyes.",
                        "eye 4": "Round Eyes.",
                        "eye 5": "Angered Eyes.",
                        "eye 6": "Wide Eyes.",
                        "eye 7": "Droopy Eyes.",
                        "eye 8": "Thin Almond Eyes.",
                        "eye 9": "Round Almond Eyes.",
                        "eye 10": "Big Round Eyes.",
                        "eye 11": " Very Big Eyes.",
                        "eye 12": "Asian Eyes.",
                        "eye 13": "Hooded Eyes.",
                        "eye 14": "Angled Eyes.",
                        "eye 15": "Big Hooded Eyes.",
                        "eye 16": "Wide Small Eyes.",
                        "eye 17": "Small Droopy Eyes.",
                        "eye 18": "Big Titled Eyes.",
                        "eyelash 1": "No Lash.",
                        "eyelash 2": "Wing Lashes.",
                        "eyelash 3": "Outward Lashes.",
                        "eyelash 4": "Rounded Narrow Lashes.",
                        "eye_details 1": "No Detail.",
                        "eye_details 2": "Under Eye Line.",
                        "eye_details 3": "Small underline",
                        "eye_details 4": "Corner Wrinkles.",
                        "eye_details 5": "Under Eye Deep Lines.",
                        "eye_details 6": "Corner Wrinkles and Minor Line.",
                        "eye_details 7": "Under Bags.",
                        "eye_details 8": "Under Eye Line.",
                        "face_lines 1": "No Line.",
                        "face_lines 2": "Forehead Line.",
                        "face_lines 3": "Forehead Lines.",
                        "face_lines 4": "Forehead C Line.",
                        "face_lines 5": "Curve Line",
                        "face_lines 6": "Frown Lines",
                        "face_lines 7": "Deep Frown lines",
                        "face_lines 8": "Frown and Headline",
                        "face_lines 9": "Multiple Lines",
                        "face_lines 10": "C line and Frown",
                        "face_lines 11": "Curve Lines with Forehead Lines.",
                        "face_lines 12": "Repetition",
                        "face_lines 13": "Repetition",
                        "face_lines 14": "Repetition",
                        "face_lines 15": "Repetition",
                        "face_lines 16": "Wound on Forehead",
                        "ear 1": "Square Ears.",
                        "ear 2": "Round Ears.",
                        "ear 3": "Small Ears.",
                        "ear 4": "Long Ears.",
                        "ear 5": " Narrow Ears.",
                        "ear 6": "Long Ears.",
                        "ear 7": "Narrow and Long Ears.",
                        "ear 8": "Big and Long Ears",
                        "ear 9": "Titled Back Ears",
                        "earring 1": "No Earring.",
                        "earring 2": "Mini Ear-ring.",
                        "earring 3": "Stud.",
                        "cheek_details 1": "Normal Cheeks.",
                        "cheek_details 2": " Mole Under Eyes Cheeks.",
                        "cheek_details 3": "Lower Bone Cheeks.",
                        "cheek_details 4": "Dimple Cheeks.",
                        "cheek_details 5": "Deep Dimple Cheeks.",
                        "cheek_details 6": "Deep Cheeks.",
                        "cheek_details 7": "Slightly Chubby Cheeks.",
                        "cheek_details 8": "Detailed Cheekbones.",
                        "cheek_details 9": "Heart-Shaped Cheeks.",
                        "cheek_details 10": "Diamond Cheeks.",
                        "cheek_details 11": "Round Cheeks.",
                        "cheek_details 12": "Heptagon Cheeks.",
                        "glasses 1": "Rectangle",
                        "glasses 2": "hick Rectangular Frame",
                        "glasses 3": "hin Rectangular",
                        "glasses 4": "road Brown Frame",
                        "glasses 5": "quare",
                        "glasses 6": "hick Square look",
                        "glasses 7": "hin Rectangular with Colored Glasses",
                        "glasses 8": "eflection Style",
                        "glasses 9": "lack Rectangular",
                        "glasses 10": "Stripes Glasses",
                        "glasses 11": "Thick Transparent",
                        "glasses 12": "Reflection Glass",
                        "glasses 13": "Black",
                        "glasses 14": "Thick Stripes Style",
                        "glasses 15": "Professor Look",
                        "glasses 16": "Shining Glass",
                        "glasses 17": "Black Outright",
                        "glasses 18": "Thick Stripes on Black",
                        "glasses 19": "Thick Black Outlines",
                        "glasses 20": "Reflection Glasses",
                        "glasses 21": "Pure Black",
                        "glasses 22": "Two Stripes on Black",
                        "glasses 23": "Square Look",
                        "glasses 24": "Transparent Look",
                        "glasses 25": "Black Square",
                        "glasses 26": "Stripes",
                        "glasses 27": "Thick",
                        "glasses 28": "Broad look",
                        "glasses 29": "Broad Frame with Reflection Glass",
                        "glasses 30": "Black Broad Look",
                        "glasses 31": "Stripes Look",
                        "glasses 32": "Angled Frame",
                        "glasses 33": "Angled Frame with Colored Glass",
                        "glasses 34": "Angled Reflection Glass",
                        "glasses 35": "Black Angled Frame",
                        "glasses 36": "Stripes Angled Frame",
                        "glasses 37": "Swimming Style Frame",
                        "glasses 38": "Swimming Style Colored Glass",
                        "glasses 39": "Stripes Swimming Style",
                        "glasses 40": "Black Swimming Style",
                        "glasses 41": "Stripes Swimming Style Glass",
                        "glasses 42": "Oval Touch Frame",
                        "glasses 43": "Colored Oval Touch Frame",
                        "glasses 44": "Shiny Oval Touch",
                        "glasses 45": "Black Oval Touch",
                        "glasses 46": "Stripes Oval Touch",
                        "glasses 47": "Round Frame",
                        "glasses 48": "Colored Glass Round Frame",
                        "glasses 49": "Round Reflection Style",
                        "glasses 50": "Round Black Glass",
                        "glasses 51": "Stripes Round Glass",
                        "glasses 52": "Single Side Glass Frame",
                        "glasses 53": "Single Glass with String",
                        "glasses 54": "Thick Square Shape",
                        "glasses 55": "Colored Glass Square Look",
                        "glasses 56": "Square Frame with Reflection Look",
                        "glasses 57": "Sun Glasses",
                        "glasses 58": "Sun Glasses with Stripes",
                        "glasses 59": "Multi-Shade Style",
                        "glasses 60": "Deep Oval",
                        "glasses 61": "Oval with Colored Glass",
                        "glasses 62": "Oval with Reflection",
                        "glasses 63": "Oval Sun Glasses",
                        "glasses 64": "Oval Sun Glasses with Stripes",
                        "glasses 65": "Just Glass Spectacles",
                        "glasses 66": "Colored Glass Look",
                        "glasses 67": "Shadow on Glass",
                        "glasses 68": "Narrow Sun Glasses",
                        "glasses 69": "Narrow Striped Look",
                        "glasses 70": "City Look",
                        "glasses 71": "City Style with Colored Glass",
                        "glasses 72": " City Style with Reflection",
                        "glasses 73": "Unique 702 Sun Glasses",
                        "glasses 74": "Unique 701 Striped Sun Glasses",
                        "glasses 75": "Pop Star Look 550",
                        "glasses 76": "Professor 401",
                        "glasses 77": "Space A28",
                        "glasses 78": "Heart for You",
                        "glasses 79": "Whirlpool",
                        "glasses 80": "Professor 474",
                        "glasses 81": "Eye Shape Frame",
                        "glasses 82": "Eye Mask 101",
                        "hair 1": "Black Shoulder Length Hair",
                        "hair 2": "Straight Black Side Parted Long Hair",
                        "hair 3": "Layered Black Middle Parted Long Hair",
                        "hair 4": "Wavy Black Shoulder Length Hair",
                        "hair 5": "Black Side Parted and Twisted Shoulder Length Hair",
                        "hair 6": "Straight Black Middle Parted Long Hair",
                        "hair 7": "Straight Black Hair With Curtain Bangs",
                        "hair 8": "Side Parted Black Hair With Feather Cutting",
                        "hair 9": "Medium Layered Black Hair",
                        "hair 10": " Black Straight Puffed Hair",
                        "hair 11": " Black Wedge Hair",
                        "hair 12": " Black Shag Wavy Hair",
                        "hair 13": " Black Wavy Left Parted Side Parted Hair",
                        "hair 14": " Short Wavy Right Parted Black Hair",
                        "hair 15": " Short Wavy Asymmetrical Hair",
                        "hair 16": " Short Black Hair With Curtain Bangs",
                        "hair 17": " Short Black Hair With Soft Waves",
                        "hair 18": " Long Black Hair With Soft Waves",
                        "hair 19": " Long Black Hair Middle Parted and Tied",
                        "hair 20": " Short Black Hair With Classic Curls",
                        "hair 21": " Short Black Hair With Defined Waves",
                        "hair 22": " Short Black Hair Puffed With Defined Waves",
                        "hair 23": " Short Black Side Parted Spiral Curled Hair",
                        "hair 24": " Short Black Spiral Curled Hair With Curtain Bangs",
                        "hair 25": " Black Afro Hair",
                        "hair 26": " Short Black Spiral Curled Hair",
                        "hair 27": " Short Black Left Side Parted Spiral Curled Hair",
                        "hair 28": " Short Black Dreadlocks Hair Curls",
                        "hair 29": " Short Black Dreadlocks Half Tied Hair",
                        "hair 30": " Black Dreadlocks Hair Tied In a Pony",
                        "hair 31": " Black Trimmed Afro Hair",
                        "hair 32": " Black Sleek Hair",
                        "hair 33": " Black Sleek Pony Hair",
                        "hair 34": " (Repeated)",
                        "hair 35": " (Repeated)",
                        "hair 36": " Black Sleek Bun Hair",
                        "hair 37": " Black Curly Hair Top Knot",
                        "hair 38": " Black Short Bob Hair",
                        "hair 39": " Black Short Hair With Side Fringe",
                        "hair 40": " Black Side Parted Short Hair",
                        "hair 41": " Black Short Hair With Middle Fringe",
                        "hair 42": " Black Short Middle Parted Hair",
                        "hair 43": " Black Short Shag Hair",
                        "hair 44": " Black Short Hair With Layers",
                        "hair 45": " Black Layered Bob Hair",
                        "hair 46": " Short Black Hair With Side Fringe",
                        "hair 47": " Short Black Hair With Shaggy Bangs",
                        "hair 48": " Black Short Hair With Asymmetrical Bangs",
                        "hair 49": " Short Black Hair With Baby Bangs",
                        "hair 50": " Black Pixie Cut",
                        "hair 51": "Short Black Hair With Two Ponytails",
                        "hair 52": "Short Black Hair With Layers",
                        "hair 53": "Short Black Wavy Wavy Hair",
                        "hair 54": "Short Black Side Parted Hair",
                        "hair 55": "Short Black Upsweep Hair",
                        "hair 56": "Short Black Bedhead Hair",
                        "hair 57": "Short Black Wavy Whirly Hair",
                        "hair 58": "Short Black Asymmetrical Hair",
                        "hair 59": "Short Black Wavy Curvy Hair With Shag Cut",
                        "hair 60": "Short Black Boy Cut Hair",
                        "hair 61": "Short Black Boy Pixie Cut Hair",
                        "hair 62": "Short Black Boy Cut Hair With Shag Cut",
                        "hair 63": "Short Black Straight Hair Curved Downside",
                        "hair 64": "Short Black Hair With Soft Curls",
                        "hair 65": "Black Shoulder Length Hair With Deep Waves",
                        "hair 66": "Short Black Wavy Hair With Short Layers",
                        "hair 67": "Short Black Curly Hair",
                        "hair 68": "Short Black Hair With Classic Waves",
                        "hair 69": "Short Black Hair With Side Wedge",
                        "hair 70": "Short Black Hair With Corkscrews",
                        "hair 71": "Short Black Classic Waves With Bangs",
                        "hair 72": "Black Shoulder Length Hair With Loose Dreadlocks",
                        "hair 73": "Black Under-Cut Boy Hair",
                        "hair 74": "Black Hair Boy Cut With Asymmetrical Cut",
                        "hair 75": "Black Hair Boy Cut With Bedhead Bangs",
                        "hair 76": "Short Black Bowl Cut",
                        "hair 77": "Short Black Boy Hair With Asymmetrical Cut",
                        "hair 78": "Short Black Boy Shag Cut",
                        "hair 79": "Short Black Boy Cut With Wedge Cut",
                        "hair 80": "Short Black Hair With Spikes",
                        "hair 81": "Short Black Hair With Deep Waves",
                        "hair 82": "Short Black Hair With Undercut",
                        "hair 83": "Short Black Hair With Short And Trimmed Side Wedge",
                        "hair 84": "Short Black Hair With Trimmed Boy Cut",
                        "hair 85": "Short Black Tomboy Wavy Pixie Cut",
                        "hair 86": "Black Short And Slicked Tomboy Hair",
                        "hair 87": "Short Black Curly Mullet Hair",
                        "hair 88": "Short Black Wavy Tomboy Hair Cut",
                        "hair 89": "Short Black Curly Tomboy Hair Cut",
                        "hair 90": "Short Black Free Tomboy Hair Cut",
                        "hair 91": "Black Trimmed Tomboy Hair Cut",
                        "hair 92": "Black Trimmed Afro Hair",
                        "hair 93": "Black Trimmed Afro Hair With Slightly Middle Parted",
                        "hair 94": "Black Trimmed Afro Hair With Caesar",
                        "hair 95": "Black Afro Hair Bowl Cut",
                        "hair 96": "Black Buzz Tomboy Hair Cut",
                        "hair 97": "Black Coiled Curly Tomboy Hair",
                        "hair 98": "Short Black Tied Dreadlocks",
                        "hair 99": "Bald Tomboy Hair Cut",
                        "hair 100": "Bald Fade Tomboy Hair Cut",
                        "hair 101": "Black Frontal Bald Hair",
                        "hair 102": "Black Slightly Curled Frontal Bald Hair",
                        "hair 103": "Black Wavy Frontal Bald Hair",
                        "hair 104": "Black Bald Buzz Cut Hair",
                        "hair 105": "Short Black Bald Wedge Cut",
                        "hair 106": "Black Half Bald Hair",
                        "hair 107": "Black Balding Crown Hair",
                        "hair 108": "Full Bald With Ear Hair",
                        "hair 109": "Full Bald",
                        "hat 1": "No Hat",
                        "hat 2": "Half Hat Cap with Contrast",
                        "hat 3": "Maroon Ivy Cap with Band",
                        "hat 4": "Pure Grey Half Hat",
                        "hat 5": "Half Hat with Flower",
                        "hat 6": "Beret Style Hat",
                        "hat 7": "Grey Trendy Ivy",
                        "hat 8": "Tilted Ivy Look",
                        "hat 9": "Round Bow Style",
                        "hat 10": "Band Look",
                        "hat 11": "Bucket Style 101",
                        "hat 12": "Braid Hat",
                        "hat 13": "Scarf Style",
                        "hat 14": "Turban Look",
                        "hat 15": "Bouncy Hat",
                        "hat 16": "Broad Band Hat",
                        "hat 17": "Bobble Hat Basic",
                        "hat 18": "Bobble Hat Trendy",
                        "hat 19": "Bobble and Ivy Merge",
                        "hat 20": "Towel Style Hat",
                        "hat 21": "Multi Color Band Look",
                        "hat 22": "Modern Buckle Hat",
                        "hat 23": "Colorful Buckle Look",
                        "hat 24": "Inverted Baseball Hat",
                        "hat 25": "Half Hat Ivy Look",
                        "hat 26": "Round Hat",
                        "hat 27": "Stylish Brown Ivy",
                        "hat 28": "Trendy Bowler Hat",
                        "hat 29": "Top Hat",
                        "hat 30": "Fedora Look",
                        "hat 31": "Boater Hat",
                        "hat 32": "Pith Helmet Look",
                        "hat 33": "Tiny Band Hat",
                        "hat 34": "Beret Hat",
                        "hat 35": "Sikh Style",
                        "hat 36": "Turban Pagri Look",
                        "hat 37": "Round Wavy Hat",
                        "hat 38": "Bucket Style",
                        "hat 39": "Detailed Bowler Hat",
                        "hat 40": "Cop Hat",
                        "hat 41": "Bob Style",
                        "hat 42": "Nurse Hat",
                        "hat 43": "Crown Hat",
                        "hat 44": "Funky Crown Hat",
                        "hat 45": "Chef Style Hat",
                        "hat 46": "Green Half Hat",
                        "hat 47": "Triangle Hat",
                        "hat 48": "Curvy Hat",
                        "hat 49": "Sailor Style Hat",
                        "hat 50": "Simple Flower",
                        "hat 51": "Seed",
                        "hat 52": "Rose",
                        "hat 53": "Miniscule Band",
                        "hat 54": "Bow",
                        "hat 55": "Brown Hair Band",
                        "hat 56": "Modern Ring Hat",
                        "hat 57": "Band with Bow",
                        "hat 58": "Pinky Headphone",
                        "hat 59": "Boat Shape Hat",
                        "hat 60": "Designed Boat Hat",
                        "hat 61": "No Hat",
                        "hat 62": "Arrow",
                        "hat 63": "Rabbit Ears",
                        "hat 64": "Multi-Shade Bowler Hat",
                        "hat 65": "Antenna Band",
                        "hat 66": "Long Bucket Look",
                        "hat 67": "Top Hat with Ornament",
                        "hat 68": "Animal Hat",
                        "hat 69": "Egyptian Hat",
                        "hat 70": "Hard Conventional Hat",
                        "hat 71": "Boot Hat",
                        "hat 72": "Furry Long hat",
                        "hat 73": "Helmet Hat",
                        "hat 74": "Christmas Style",
                        "hat 75": "Santa Hat",
                        "hat 76": "Halo on Head",
                        "hat 77": "Horns on Head",
                        "hat 78": "Unique Horns",
                        "hat 79": "Creative Raised Hat",
                        "hat 80": "Top Style Multi-Shade",
                        "hat 81": "Designer Hat",
                        "hat 82": "Basic Headphones",
                        "hat 83": "Single Ear Headphone",
                        "hat 84": "Detailed Hat",
                        "hat 85": "Mask-Cum-Hat",
                        "hat 86": "Horn Style Trendy Hat",
                        "hat 87": "Round Head Helmet Look",
                        "hat 88": "Umbrella Style Helmet Hat",
                        "hat 89": "Funky Helmet Hat",
                        "hat 90": "Sailor Style Hat",
                        "hat 91": "Gigantic Balloon Hat",
                        "hat 92": "Graduate Hat",
                        "hat 93": "Top Patched Hat",
                        "hat 94": "Cricket Helmet Hat",
                        "hat 95": "Blue Trapper Hat",
                        "hat 96": "Shielded Hard Hat",
                        "hat 97": "Rescue Hard Hat",
                        "hat 98": "Trapper Cozy Hat",
                        "hat 99": "Unique Helmet Hat",
                        "hat 100": "Gigantic Cover Hat",
                        "hat 101": "Vendor’s Turban Hat",
                        "hat 102": "Lawyer’s Style Hat",
                        "hat 103": "Rescue Round Hat",
                        "hat 104": "Trendy Triangle Hat",
                        "hat 105": "Fire Trendy Hat",
                        "hat 106": "Bomb Hat",
                        "jaw 1": "Round-Shaped Jaw",
                        "jaw 2": "Oval Shaped Jaw",
                        "jaw 3": "Triangle Shaped Jaw",
                        "jaw 4": "Trapeze Shaped Jaw",
                        "jaw 5": "Slightly Square-Shaped Jaw",
                        "jaw 6": "Heart-Shaped Jaw",
                        "jaw 7": "Inverted Triangle Shaped Jaw",
                        "jaw 8": "Circle Shaped Jaw",
                        "jaw 9": "Diamond Shaped Jaw",
                        "mouth 1": "Inverted Mouth",
                        "mouth 2": "Thin Mouth",
                        "mouth 3": "Downward-turned Mouth",
                        "mouth 4": "Small Inverted Mouth",
                        "mouth 5": "Narrowed Mouth",
                        "mouth 6": "Heart-shaped Mouth",
                        "mouth 7": "Full Lips Mouth",
                        "mouth 8": "Pencil-thin Mouth",
                        "mouth 9": "Wide Mouth",
                        "nose 1": "Hooked Nose",
                        "nose 2": "Droopy Nose",
                        "nose 3": "Grecian Nose",
                        "nose 4": "Snub Nose",
                        "nose 5": "Button Nose",
                        "nose 6": "Roman Nose",
                        "nose 7": "Funnel Nose",
                        "nose 8": "Aquiline Nose",
                        "nose 9": "Downward Roman Nose",
                        "nose 10": "Straight Nose",
                        "nose 11": "Nubian Nose",
                        "nose 12": "Fleshy Nose",
                        "nose 13": "Snubby Nose",
                        "nose 14": "Small Button Nose",
                        "nose 15": "Upturned Nose",
                        "nose 16": "Roma Nose",
                        "nose 17": "Grecian Nose Upward",
                        "nose 18": "Small Upturned Nose",
                        "pupil 1": "Black Big Round Pupil",
                        "pupil 2": "Black Droopy Pupil",
                        "pupil 3": "Black Thin Almond Pupil",
                        "pupil 4": "Brown Hooded Pupil",
                        "pupil 5": "Brown Droopy Pupil",
                        "pupil 6": "Brown Thin Almond Pupil",
                        "pupil 7": "Sparkling Brown Roundish-Almond Pupil",
                        "pupil 8": "Sparkling Brown Droopy Pupil",
                        "pupil 9": "Sparkling Brown Thin Almond Pupil",
                        "blush_tone 1": "No blush",
                        "blush_tone 2": "Rose Subtle",
                        "blush_tone 3": "Cornalina Blush",
                        "blush_tone 4": "Dark Cornalina Blush",
                        "blush_tone 5": "Carmim Blush",
                        "blush_tone 6": "Pure Pink",
                        "blush_tone 7": "Blended Pink",
                        "blush_tone 8": "Baby Pink",
                        "blush_tone 9": "Rosa Escuro Blush",
                        "blush_tone 10": "Ruby Rose Blush",
                        "blush_tone 11": "Puce Blush",
                        "blush_tone 12": "Dark Puce Blush",
                        "blush_tone 13": "Violet Subtle Blush",
                        "blush_tone 14": "Dark Rosa Blush",
                        "blush_tone 15": "Purple Blush",
                        "blush_tone 16": "Blue Tone Blush",
                        "blush_tone 17": "Greyish Blush",
                        "blush_tone 18": "Sea Green Blush",
                        "blush_tone 19": "Light Greenish Blush",
                        "blush_tone 20": "Blended Green",
                        "blush_tone 21": "Subtle Peach",
                        "blush_tone 22": "Rusty Tone",
                        "blush_tone 23": "Persian Brownish Tone",
                        "blush_tone 24": "Orange Red Tones",
                        "blush_tone 25": "Subtle Mauve Tape",
                        "blush_tone 26": "Dark Mauve Tape",
                        "blush_tone 27": "Light Grey Tone",
                        "blush_tone 28": "Blended Subtle Greyish",
                        "blush_tone 29": "Grey Blend",
                        "blush_tone 30": "Clouded Grey Blend",
                        "blush_tone 31": "Light Natural Puce",
                        "blush_tone 32": "Light Stone Grey",
                        "blush_tone 33": "Subtle Intrinsic Tone",
                        "blush_tone 34": "Subtle Blue Blush",
                        "blush_tone 35": "Smoked Pearl",
                        "brow_tone 1": "Jet Black",
                        "brow_tone 2": "Dark Black",
                        "brow_tone 3": "Faded Black",
                        "brow_tone 4": "Black",
                        "brow_tone 5": "Black",
                        "brow_tone 6": "Faded Black",
                        "brow_tone 7": "Dark Brown",
                        "brow_tone 8": "Faded Brown Black",
                        "brow_tone 9": "Brownish",
                        "brow_tone 10": "Choco Brown",
                        "brow_tone 11": "Auburn",
                        "brow_tone 12": "Blonde Brown",
                        "brow_tone 13": "Brown Black",
                        "brow_tone 14": "Mocha",
                        "brow_tone 15": "Matte Gold",
                        "brow_tone 16": "Almond",
                        "brow_tone 17": "Light Brown",
                        "brow_tone 18": "Blonde",
                        "brow_tone 19": "Grey",
                        "brow_tone 20": "Pure Grey",
                        "brow_tone 21": "Bright Blue",
                        "brow_tone 22": "Cloud Grey",
                        "brow_tone 23": "Mix Black Tone",
                        "brow_tone 24": "Black",
                        "brow_tone 25": "Light Greyish",
                        "brow_tone 26": "Black Tone",
                        "brow_tone 27": "Bright Blue",
                        "brow_tone 28": "Bright Green Mix",
                        "brow_tone 29": "Auburn Tone",
                        "brow_tone 30": "Pure Auburn",
                        "brow_tone 31": "Red Tone",
                        "brow_tone 32": "Dark Auburn Black",
                        "brow_tone 33": "Mix Auburn Tone",
                        "brow_tone 34": "Mix Black",
                        "brow_tone 35": "Black",
                        "brow_tone 36": "Jet Black",
                        "brow_tone 37": "Blue Grey Mix",
                        "brow_tone 38": "Shocking Blue",
                        "brow_tone 39": "Cobalt Blue",
                        "brow_tone 40": "Black",
                        "brow_tone 41": "Green Black Mix",
                        "brow_tone 42": "Bright Parrot Green",
                        "brow_tone 43": "Cadium Green",
                        "brow_tone 44": "Dark Black Green",
                        "brow_tone 45": "Fuchsia Pink",
                        "brow_tone 46": "Purplish",
                        "brow_tone 47": "Dark Purple",
                        "brow_tone 48": "Bright Purple",
                        "brow_tone 49": "Mix Purple and Blue",
                        "brow_tone 50": "Dark Pure Purple",
                        "brow_tone 51": "Black Purple",
                        "brow_tone 52": "Black",
                        "eyeshadow_tone 1": "No shadow",
                        "eyeshadow_tone 2": "Pinkish",
                        "eyeshadow_tone 3": "Fiesta Peach",
                        "eyeshadow_tone 4": "Caramel",
                        "eyeshadow_tone 5": "Hazelnut Toasted",
                        "eyeshadow_tone 6": "Lustrous",
                        "eyeshadow_tone 7": "Ice Cold",
                        "eyeshadow_tone 8": "Old Saint Pink",
                        "eyeshadow_tone 9": "Marlena Pink",
                        "eyeshadow_tone 10": "Cherry Cola",
                        "eyeshadow_tone 11": "Lavender",
                        "eyeshadow_tone 12": "Jungle",
                        "eyeshadow_tone 13": "Purple",
                        "eyeshadow_tone 14": "Anarchy",
                        "eyeshadow_tone 15": "Vibrant Grape",
                        "eyeshadow_tone 16": "Reflection",
                        "eyeshadow_tone 17": "Cobalt",
                        "eyeshadow_tone 18": "Iris",
                        "eyeshadow_tone 19": "Aqua",
                        "eyeshadow_tone 20": "Ocean",
                        "eyeshadow_tone 21": "Rule",
                        "eyeshadow_tone 22": "Coral",
                        "eyeshadow_tone 23": "Red Brick",
                        "eyeshadow_tone 24": "Peach",
                        "eyeshadow_tone 25": "Cocoa",
                        "eyeshadow_tone 26": "Quarry",
                        "eyeshadow_tone 27": "Sweet Lust",
                        "eyeshadow_tone 28": "Swish",
                        "eyeshadow_tone 29": "Print",
                        "eyeshadow_tone 30": "Cloudy",
                        "eyeshadow_tone 31": "Dairy",
                        "eyeshadow_tone 32": "Motif",
                        "eyeshadow_tone 33": "Tilt",
                        "eyeshadow_tone 34": "Plumage",
                        "eyeshadow_tone 35": "Typographic",
                        "hair_tone 1": "Natural Black",
                        "hair_tone 2": "Dark Greyish Black",
                        "hair_tone 3": "Dark Brown Black",
                        "hair_tone 4": "Ruby Black",
                        "hair_tone 5": "Dark Grey",
                        "hair_tone 6": "Ruivo Natural",
                        "hair_tone 7": "Chocolate Brown",
                        "hair_tone 8": "Amber",
                        "hair_tone 9": "Hot Toffee",
                        "hair_tone 10": "Golden Blonde",
                        "hair_tone 11": "Caramel Blonde",
                        "hair_tone 12": "Light Blonde",
                        "hair_tone 13": "Light Ash Blonde",
                        "hair_tone 14": "Sunflower Blonde",
                        "hair_tone 15": "Light Ash Blonde",
                        "hair_tone 16": "Pure Diamond Blonde",
                        "hair_tone 17": "Swedish Blonde",
                        "hair_tone 18": "Diamond Blonde",
                        "hair_tone 19": "Honey Blonde",
                        "hair_tone 20": "Vanilla Cream Blonde",
                        "hair_tone 21": "Silver Shade",
                        "hair_tone 22": "Silver Fox",
                        "hair_tone 23": "Grey",
                        "hair_tone 24": "Dark Grey",
                        "hair_tone 25": "Faded Grey",
                        "hair_tone 26": "Mix Grey",
                        "hair_tone 27": "Mystic Blue",
                        "hair_tone 28": "Lemon",
                        "hair_tone 29": "Mustard",
                        "hair_tone 30": "Medium Auburn",
                        "hair_tone 31": "Mocha",
                        "hair_tone 32": "Copper",
                        "hair_tone 33": "Copper Red",
                        "hair_tone 34": "Reddish Dark Blonde",
                        "hair_tone 35": "Burgundy",
                        "hair_tone 36": "Dark Brown",
                        "hair_tone 37": "Azure",
                        "hair_tone 38": "Royal Blue",
                        "hair_tone 39": "Voodoo Blue",
                        "hair_tone 40": "Midnight Hues",
                        "hair_tone 41": "Light Green Blonde",
                        "hair_tone 42": "Funky Green",
                        "hair_tone 43": "Beetle Green",
                        "hair_tone 44": "Smokey Green",
                        "hair_tone 45": "Funky Subtle Pink",
                        "hair_tone 46": "Dreamy Purple",
                        "hair_tone 47": "Deep Magenta",
                        "hair_tone 48": "Wild Orchid",
                        "hair_tone 49": "Baby Blue",
                        "hair_tone 50": "Grape Hues",
                        "hair_tone 51": "Plum",
                        "hair_tone 52": "Magenta",
                        "lipstick_tone 1": "No lipstick look",
                        "lipstick_tone 2": "Soft Rose",
                        "lipstick_tone 3": "Red Divine",
                        "lipstick_tone 4": "Maroon Diva",
                        "lipstick_tone 5": "Dark Expresso",
                        "lipstick_tone 6": "Lavender Fields",
                        "lipstick_tone 7": "Pink Fuchsia",
                        "lipstick_tone 8": "Pink Periwinkle",
                        "lipstick_tone 9": "Terra Cota",
                        "lipstick_tone 10": "Dark Diva",
                        "lipstick_tone 11": "Black Cherry",
                        "lipstick_tone 12": "Grape Divine",
                        "lipstick_tone 13": "Plum Look",
                        "lipstick_tone 14": "Fantasy",
                        "lipstick_tone 15": "Cyber",
                        "lipstick_tone 16": "Blue Vibes",
                        "lipstick_tone 17": "Cobalt Hues",
                        "lipstick_tone 18": "Turquoise Dive",
                        "lipstick_tone 19": "Green Sea Bed",
                        "lipstick_tone 20": "Smoky Green Lips",
                        "lipstick_tone 21": "Nude Peach Vines",
                        "lipstick_tone 22": "Orange Tango",
                        "lipstick_tone 23": "Lady Danger",
                        "lipstick_tone 24": "Vibrant",
                        "lipstick_tone 25": "Viva Glam",
                        "lipstick_tone 26": "Pink Suga",
                        "lipstick_tone 27": "Desert",
                        "lipstick_tone 28": "Caramel Nude",
                        "lipstick_tone 29": "Pink Gloss",
                        "lipstick_tone 30": "Wine Room",
                        "lipstick_tone 31": "Pick Lemon",
                        "lipstick_tone 32": "Carrot Gold",
                        "lipstick_tone 33": "Doll House Pink",
                        "lipstick_tone 34": "Desert Taupe",
                        "lipstick_tone 35": "Expresso Black",
                        "pupil_tone 1": "Dark Brown",
                        "pupil_tone 2": "Honey",
                        "pupil_tone 3": "Pure Hazel",
                        "pupil_tone 4": "Sapphire",
                        "pupil_tone 5": "Brilliant Blue",
                        "pupil_tone 6": "Satin Grey",
                        "pupil_tone 7": "Green",
                        "pupil_tone 8": "Emerald Green",
                        "pupil_tone 10": "Black Brown",
                        "pupil_tone 11": "Amethyst",
                        "pupil_tone 12": "Satin Grey",
                        "pupil_tone 13": "Marble Grey",
                        "pupil_tone 14": "Topaz Blue",
                        "pupil_tone 15": "Blue Pure",
                        "pupil_tone 16": "Deep Hazel",
                        "pupil_tone 17": "Natural Gray",
                        "pupil_tone 18": "Startling Gray",
                        "skin_tone 1": "Brown",
                        "skin_tone 2": "Pinkish White",
                        "skin_tone 3": "Wheat Brown",
                        "skin_tone 4": "Greyish Black",
                        "skin_tone 5": "Bronze",
                        "skin_tone 6": "Pinkish Sand",
                        "skin_tone 7": "Rose Beige",
                        "skin_tone 8": "Expresso",
                        "skin_tone 9": "Band",
                        "skin_tone 10": "Limestone",
                        "skin_tone 11": "Warm Ivory",
                        "skin_tone 12": "Dark Almond",
                        "skin_tone 13": "Limestone",
                        "skin_tone 14": "Ivory",
                        "skin_tone 15": "Beige",
                        "skin_tone 16": "Dark Expresso",
                        "skin_tone 17": "Dark Ivory",
                        "skin_tone 18": "Pale Ivory",
                        "skin_tone 19": "Dim Ivory",
                        "skin_tone 20": "Umber",
                        "skin_tone 21": "Porcelain",
                        "skin_tone 22": "Light Pink",
                        "skin_tone 23": "Pale Limestone",
                        "skin_tone 24": "Chestnut",
                        "skin_tone 25": "Baby Purple",
                        "skin_tone 26": "Bright White",
                        "skin_tone 27": "White Mix",
                        "skin_tone 28": "Dark Chestnut",
                        "skin_tone 29": "Mustard",
                        "skin_tone 30": "Yellow",
                        "skin_tone 31": "Blue",
                        "skin_tone 32": "Bright Purple",
                        "skin_tone 33": "Red",
                        "skin_tone 34": "Green",
                        "skin_tone 35": "Royal Blue",
                        "skin_tone 36": "Grape Purple",
                        "skin_tone 37": "Peach",
                        "skin_tone 38": "Turquoise",
                        "skin_tone 39": "Azure",
                        "skin_tone 40": "Light Purple",
                        "body 1": "Slim Body With Broad Shoulders",
                        "body 2": "Slim Body With Narrowed Shoulders",
                        "body 3": "Slender Body With Wide Shoulders",
                        "body 4": "Plump Body",
                        "body 5": "Chubby Body",
                        "face_proportion 1": "Diamond",
                        "face_proportion 2": "Heart-Shape",
                        "face_proportion 3": "Triangular",
                        "face_proportion 4": "Ellipse",
                        "face_proportion 5": "Trapeze",
                        "face_proportion 6": "Rectangle",
                        "face_proportion 7": "Oval",
                        "face_proportion 8": "Round",
                        "face_proportion 9": "Square",
                    }
                }
            ]
        }
    },
    props: {
        msg: String,
    },
    mounted() {
        this.setLibmojiData()
        this.randomize();
    },
    methods: {
        setLibmojiData() {
            this.libMojiData.genders = libmoji.genders;
            this.libMojiData.styles = libmoji.styles;
            this.libMojiData.poses = libmoji.poses;
            this.generateTraits()
            this.libMojiData.brands = libmoji.getBrands(this.choices.genderStr);
            this.libMojiData.outfits = libmoji.getOutfits(this.libMojiData.brands[this.choices.brand]);
        },
        generateTraits() {
            this.choices.genderStr = this.choices.gender == 1 ? 'male' : 'female';
            if (this.choices.style == 1) {
                this.choices.styleStr = 'bitstrips'
            } else if (this.choices.style == 4) {
                this.choices.styleStr = 'bitmoji'
            } else if (this.choices.style == 5) {
                this.choices.styleStr = 'cm'
            }
            this.libMojiData.traits = libmoji.getTraits(this.choices.genderStr, this.choices.styleStr);
        },
        generateOutfits() {
            this.libMojiData.outfits = libmoji.getOutfits(this.libMojiData.brands[this.choices.brand]);
            // this.libMojiData.outfits.forEach(function (item) {
            //     item.outfit = this.slugs.outfits[item.outfit];
            //     alert(item.outfit);
            // });
            this.choices.outfit = 0;
            this.generateAvatar()
        },
        changeStyle() {
            this.generateTraits()
        },
        generateAvatar() {
            let choices = this.choices;

            let trait = [];
            const traitKeys = Object.keys(choices.traits);
            const traitValues = Object.values(choices.traits);
            for (let i = 0; i < traitValues.length; i++) {
                trait.push([
                    traitKeys[i], traitValues[i]
                ])
            }

            let outfit = this.libMojiData.outfits[this.choices.outfit].id;

            this.avatar.url = libmoji.buildPreviewUrl(
                choices.pose,
                3,
                choices.gender,
                choices.style,
                choices.rotation,
                trait,
                outfit
            );
        },
        randomize() {
            let gender = libmoji.genders[libmoji.randInt(2)];
            let style = libmoji.styles[libmoji.randInt(3)];
            let traits = libmoji.randTraits(libmoji.getTraits(gender[0], style[0]));
            let outfit = libmoji.randOutfit(
                libmoji.getOutfits(libmoji.randBrand(libmoji.getBrands(gender[0])))
            );

            this.avatar.gender = gender;
            this.avatar.style = style;
            this.avatar.traits = traits;
            this.avatar.outfit = outfit;

            this.avatar.url = libmoji.buildPreviewUrl(
                "fashion",
                3,
                gender[1],
                style[1],
                0,
                traits,
                outfit
            );
        },
        profileImgUpload() {
            console.log(this.avatar.url);
            this.form.url = this.avatar.url;

            this.form.post(this.$route('profileImgUpload'), {
                replace: true,
                onSuccess: () => {
                    this.$store.dispatch('Utils/showSuccessMessage')
                    $('.modal_create_avatar').modal('hide');
                    $('.modal_create_avatar').find('form').trigger('reset');
                },
                onFinish: () => {
                    this.$store.dispatch('Utils/showErrorMessages').then(res => {
                        this.isEdit = false
                    })
                }
            })
        }
    }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
    margin: 40px 0 0;
}

ul {
    list-style-type: none;
    padding: 0;
}

li {
    display: inline-block;
    margin: 0 10px;
}

a {
    color: #42b983;
}

.container {
    width: 1280px;
    margin: 0 auto;
}

.row {
    display: flex;
}

.col-6 {
    flex: 0 1 50%;
    width: 50%
}

.sticky {
    position: sticky;
    top: -1px;
}
</style>
